"use client";

import { useState, useRef, type KeyboardEvent } from "react";
import { useRouter } from "next/navigation";
import { QRCodeSVG } from "qrcode.react";
import { AlertTriangle, Copy, Printer, Check, CheckCircle2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { genererCodesSecours } from "./actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

type Etape = "demarrage" | "qr" | "codes";

export function InscriptionTotp() {
  const router = useRouter();
  const [etape, setEtape] = useState<Etape>("demarrage");
  const [factorId, setFactorId] = useState<string | null>(null);
  const [totpUri, setTotpUri] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [code, setCode] = useState(["", "", "", "", "", ""]);
  const inputsRef = useRef<(HTMLInputElement | null)[]>([]);
  const [codesSecours, setCodesSecours] = useState<string[]>([]);
  const [erreur, setErreur] = useState<string | null>(null);
  const [enCours, setEnCours] = useState(false);

  async function demarrerInscription() {
    setErreur(null);
    setEnCours(true);
    const supabase = createClient();
    const { data, error } = await supabase.auth.mfa.enroll({ factorType: "totp" });
    setEnCours(false);

    if (error || !data) {
      setErreur("Unable to start enrollment. Please try again.");
      return;
    }

    setFactorId(data.id);
    setTotpUri(data.totp.uri);
    setSecret(data.totp.secret);
    setEtape("qr");
  }

  async function verifierCode() {
    if (!factorId) return;
    setErreur(null);
    setEnCours(true);

    const supabase = createClient();
    const codeComplet = code.join("");
    const { error } = await supabase.auth.mfa.challengeAndVerify({
      factorId,
      code: codeComplet,
    });

    if (error) {
      setEnCours(false);
      setErreur("Incorrect code. Please try again.");
      return;
    }

    const codes = await genererCodesSecours();
    setEnCours(false);
    setCodesSecours(codes);
    setEtape("codes");
  }

  function handleCodeChange(index: number, value: string) {
    if (!/^\d*$/.test(value)) return;
    const newCode = [...code];
    newCode[index] = value.slice(0, 1);
    setCode(newCode);

    if (value && index < 5) {
      inputsRef.current[index + 1]?.focus();
    }
  }

  function handleCodeKeyDown(index: number, e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      inputsRef.current[index - 1]?.focus();
    }
  }

  if (etape === "demarrage") {
    return (
      <div className="space-y-4">
        <p className="text-sm text-foreground">
          Two-factor authentication protects your account with a code generated by an app like Google Authenticator, in addition to your password.
        </p>
        {erreur && (
          <div className="rounded-lg bg-destructive-soft px-4 py-3 text-sm text-destructive flex items-start gap-2">
            <AlertTriangle className="size-4 mt-0.5 shrink-0" />
            {erreur}
          </div>
        )}
        <Button onClick={demarrerInscription} disabled={enCours} className="w-full h-12 text-base">
          {enCours ? "Preparing..." : "Enable Two-Factor Authentication"}
        </Button>
      </div>
    );
  }

  const ETAPES = ["Setup", "Verification", "Backup Codes"];
  const etapeNum = etape === "qr" ? 1 : etape === "codes" ? 2 : 0;

  if (etape === "qr") {
    return (
      <div className="space-y-6">
        <div className="flex gap-1.5">
          {ETAPES.map((_, i) => (
            <span
              key={i}
              className="h-1.5 flex-1 rounded-full"
              style={{
                background: i <= etapeNum ? "var(--success)" : "var(--success-soft)",
              }}
            />
          ))}
        </div>

        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground text-center">
          Setup · Step {etapeNum + 1} of {ETAPES.length}
        </p>

        <div className="space-y-2">
          <h2 className="text-xl font-semibold text-center">Scan QR Code</h2>
          <p className="text-sm text-center text-muted-foreground">
            Scan this code with your authenticator app, then enter the 6-digit code generated.
          </p>
        </div>

        {totpUri && (
          <div className="mx-auto flex size-52 items-center justify-center rounded-lg border-2 border-border bg-card p-3">
            <QRCodeSVG
              value={totpUri}
              size={180}
              level="M"
              aria-label="Two-factor authentication setup QR code"
            />
          </div>
        )}

        {secret && (
          <div className="rounded-lg bg-muted p-3">
            <p className="text-xs text-center text-muted-foreground mb-1">
              Can&apos;t scan? Enter this key in your app:
            </p>
            <code className="block break-all text-center font-mono text-sm text-primary">
              {secret.match(/.{1,4}/g)?.join(" ") || secret}
            </code>
          </div>
        )}

        <div className="space-y-2">
          <Label className="text-sm font-medium text-center block">
            Enter 6-digit code
          </Label>
          <div className="flex gap-2 justify-center">
            {code.map((digit, index) => (
              <Input
                key={index}
                ref={(el) => {
                  inputsRef.current[index] = el;
                }}
                type="text"
                inputMode="numeric"
                maxLength={1}
                value={digit}
                onChange={(e) => handleCodeChange(index, e.target.value)}
                onKeyDown={(e) => handleCodeKeyDown(index, e)}
                className="h-14 w-14 text-center text-xl font-semibold"
                aria-label={`Digit ${index + 1}`}
              />
            ))}
          </div>
        </div>

        {erreur && (
          <div className="rounded-lg bg-destructive-soft px-4 py-3 text-sm text-destructive flex items-start gap-2">
            <AlertTriangle className="size-4 mt-0.5 shrink-0" />
            {erreur}
          </div>
        )}

        <Button
          onClick={verifierCode}
          disabled={enCours || code.join("").length < 6}
          className="w-full h-12 text-base"
        >
          {enCours ? "Verifying..." : "Verify and Activate"}
        </Button>
      </div>
    );
  }

  async function copierCodes() {
    const texte = codesSecours.join("\n");
    await navigator.clipboard.writeText(texte);
  }

  function imprimerCodes() {
    const contenu = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>ITA Manager — Backup Codes</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 2rem; max-width: 600px; margin: 0 auto; }
            h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
            p { color: var(--muted-foreground); font-size: 0.875rem; margin-bottom: 1.5rem; }
            .codes { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; }
            code { font-family: monospace; font-size: 1rem; }
          </style>
        </head>
        <body>
          <h1>ITA Manager — Backup Codes</h1>
          <p>Keep these codes in a safe place. Each code can only be used once.</p>
          <div class="codes">
            ${codesSecours.map((c) => `<code>${c}</code>`).join("")}
          </div>
        </body>
      </html>
    `;
    const fenetre = window.open("", "_blank");
    if (fenetre) {
      fenetre.document.write(contenu);
      fenetre.document.close();
      fenetre.print();
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex gap-1.5">
        {ETAPES.map((_, i) => (
          <span
            key={i}
            className="h-1.5 flex-1 rounded-full"
            style={{
              background: i <= etapeNum ? "var(--success)" : "var(--success-soft)",
            }}
          />
        ))}
      </div>

      <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground text-center">
        Setup · Step {etapeNum + 1} of {ETAPES.length}
      </p>

      <div className="space-y-2">
        <h2 className="text-xl font-semibold text-center">Save Backup Codes</h2>
        <p className="text-sm text-center text-muted-foreground">
          These codes will never be shown again
        </p>
      </div>

      <Alert className="border-warning bg-warning-soft">
        <AlertTriangle className="size-4 text-warning" />
        <AlertTitle className="text-warning">Important</AlertTitle>
        <AlertDescription className="text-warning">
          Print or write down these codes now. They are your only recovery option if you lose your device.
        </AlertDescription>
      </Alert>

      <div className="grid grid-cols-2 gap-2 rounded-lg bg-muted p-4">
        {codesSecours.map((c) => (
          <code key={c} className="font-mono text-sm text-primary">
            {c}
          </code>
        ))}
      </div>

      <div className="flex gap-2">
        <Button variant="outline" onClick={copierCodes} className="flex-1 h-10">
          <Copy className="size-4 mr-2" />
          Copy
        </Button>
        <Button variant="outline" onClick={imprimerCodes} className="flex-1 h-10">
          <Printer className="size-4 mr-2" />
          Print
        </Button>
      </div>

      <Button onClick={() => router.push("/")} className="w-full h-12 text-base bg-success">
        <CheckCircle2 className="size-4 mr-2" />
        I&apos;ve saved my codes, access the application
      </Button>
    </div>
  );
}
